/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ano-ui/components/AButton/AButton.vue')['default']
    ACell: typeof import('ano-ui/components/ACell/ACell.vue')['default']
    ACellGroup: typeof import('ano-ui/components/ACellGroup/ACellGroup.vue')['default']
    ACheckbox: typeof import('ano-ui/components/ACheckbox/ACheckbox.vue')['default']
    ACheckboxGroup: typeof import('ano-ui/components/ACheckboxGroup/ACheckboxGroup.vue')['default']
    ACollapse: typeof import('ano-ui/components/ACollapse/ACollapse.vue')['default']
    ACollapseItem: typeof import('ano-ui/components/ACollapseItem/ACollapseItem.vue')['default']
    ANavBar: typeof import('ano-ui/components/ANavBar/ANavBar.vue')['default']
    APage: typeof import('ano-ui/components/APage/APage.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    HiCounter: typeof import('./components/HiCounter.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    UBasePage: typeof import('./components/UBasePage.vue')['default']
    UGitHubButton: typeof import('./components/UGitHubButton.vue')['default']
    UThemeSwitcher: typeof import('./components/UThemeSwitcher.vue')['default']
  }
}
